Fix release environment name
It was set to `publish` in the teams repo
(https://github.com/rust-lang/team/pull/2490), so publishing failed.

```
Error: Failed to retrieve token from Cargo registry. Status: 400. Error: The Trusted Publishing config for repository `rust-lang/rustdoc-types` does not match the environment `release` in the JWT. Expected environments: `publish`
```